sudo: false
language: rust
cache: cargo
branches:
  only:
  - master
before_script:
- cargo install mdbook --force
script:
- mdbook test
- mdbook build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash ci/deploy.sh
env:
  global:
    - secure: CkUi2Sktr7xti6hAcYguVzfEOkDSadnQlLVpNkYWOT5c+qncBUoJGh2hpZo19kjUVrcOdRGACkqh4IjIOW7IvVHCcXRRDXMxMc39EgBKNmNKKeT5xNEWt69Coae9Pq0CWvh8suMJF97yGjXprladZphHsuBkVRb5rqu0dXrzeMzF9jltKnwmCdX/HcAFmsiJ6XrPQpq/yEv8JwrWVIpD7fAfbec3MDr/DEI7iv0oCOAlykGltZ/4YzdyJLej0loAJgfod5N+3UAXxcXlJd+1rREcS8LSiN9bLAaciAENefbSgbM++ioLtP/rTXQC74O4l7h/2lIKjySVuFB2jKgUvm6xtKbNkYECt3Hjb7m4OYUGTU6Q1IO5/LYqdMCRV3Ynzf+mtL75iazbDi46gGtKPTxIcXb+fntSgzN5FaFh8bMn7BwYMXZ63F6RBymfZ3G0R4i2bR7Y66i1sEycy7M0+1kOyUH11kQikkLd786rKWIU5AyanktFgecUVi0uu9pcrymPX3PCGJiwvjJra4jFnecIXsGvx2DtM5EPXyQJJyz6CGaOarc/yBu3g7b7GpAd9QkE/NuPdv4D3Rfd0Pcq5ScWGBHeIluGz8jrpl+hQrE0QBeVEySYLHcwcFHAoXmozqOxl8YY9eVnE0g8NbDY1g4MqsmZJbufpS4k1m4UHAw=
